### ISSUE TITLE
Ensure the cents are two digit-ed

### ISSUE THREAD

**Issue by chrisarusso** [maddybvh/tipit#1]
First of all, amazing. I'm glad a bit of Monday morning math disagreement motivated you to build an app for this 👏 . However, a _true_ palindrome aficionado would include both digits in the cents side, so you may want to make that update. Right now $31.03 gives you a $7.27 tip for $38.3

**Comment by maddybvh** [comment]
Yes - I noticed that too! Thanks for filing a ticket, should be an easy fix. 

I'll let you know when it's ready for beta testing in PWA form!

**Comment by maddybvh** [comment]
Fixed this in https://github.com/maddybvh/tipit/commit/465d937dc0f7706b4a0f23ef04ae4b20b083b4e4.
Closing.
